// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pajo22.Data;

#nullable disable

namespace pajo22.Migrations
{
    [DbContext(typeof(pajo22Context))]
    [Migration("20240430000915_NewDataSeeding")]
    partial class NewDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pajo22.Models.AttributeValues", b =>
                {
                    b.Property<int>("AttributeValueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeValueID"));

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<int?>("AttributesAttributeID")
                        .HasColumnType("int");

                    b.Property<int>("ProductModelId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttributeValueID");

                    b.HasIndex("AttributeID");

                    b.HasIndex("AttributesAttributeID");

                    b.HasIndex("ProductModelId");

                    b.ToTable("AttributeValues");

                    b.HasData(
                        new
                        {
                            AttributeValueID = 111,
                            AttributeID = 111,
                            ProductModelId = 17811,
                            Value = "Android"
                        },
                        new
                        {
                            AttributeValueID = 112,
                            AttributeID = 112,
                            ProductModelId = 17811,
                            Value = "128GB"
                        },
                        new
                        {
                            AttributeValueID = 113,
                            AttributeID = 113,
                            ProductModelId = 17811,
                            Value = "6.4 inches"
                        },
                        new
                        {
                            AttributeValueID = 114,
                            AttributeID = 111,
                            ProductModelId = 278,
                            Value = "Android"
                        },
                        new
                        {
                            AttributeValueID = 115,
                            AttributeID = 112,
                            ProductModelId = 278,
                            Value = "256GB"
                        },
                        new
                        {
                            AttributeValueID = 116,
                            AttributeID = 113,
                            ProductModelId = 278,
                            Value = "6.7 inches"
                        },
                        new
                        {
                            AttributeValueID = 117,
                            AttributeID = 111,
                            ProductModelId = 378,
                            Value = "iOS"
                        },
                        new
                        {
                            AttributeValueID = 118,
                            AttributeID = 112,
                            ProductModelId = 378,
                            Value = "256GB"
                        },
                        new
                        {
                            AttributeValueID = 119,
                            AttributeID = 113,
                            ProductModelId = 378,
                            Value = "6.1 inches"
                        },
                        new
                        {
                            AttributeValueID = 1110,
                            AttributeID = 111,
                            ProductModelId = 478,
                            Value = "Android"
                        },
                        new
                        {
                            AttributeValueID = 1111,
                            AttributeID = 112,
                            ProductModelId = 478,
                            Value = "64GB"
                        },
                        new
                        {
                            AttributeValueID = 1112,
                            AttributeID = 113,
                            ProductModelId = 478,
                            Value = "6.3 inches"
                        },
                        new
                        {
                            AttributeValueID = 1113,
                            AttributeID = 111,
                            ProductModelId = 578,
                            Value = "Android"
                        },
                        new
                        {
                            AttributeValueID = 1114,
                            AttributeID = 112,
                            ProductModelId = 578,
                            Value = "32GB"
                        },
                        new
                        {
                            AttributeValueID = 1115,
                            AttributeID = 113,
                            ProductModelId = 578,
                            Value = "5.5 inches"
                        },
                        new
                        {
                            AttributeValueID = 1116,
                            AttributeID = 111,
                            ProductModelId = 678,
                            Value = "Android"
                        },
                        new
                        {
                            AttributeValueID = 1117,
                            AttributeID = 112,
                            ProductModelId = 678,
                            Value = "128GB"
                        },
                        new
                        {
                            AttributeValueID = 1118,
                            AttributeID = 113,
                            ProductModelId = 678,
                            Value = "6.2 inches"
                        },
                        new
                        {
                            AttributeValueID = 1119,
                            AttributeID = 111,
                            ProductModelId = 778,
                            Value = "Windows 10"
                        },
                        new
                        {
                            AttributeValueID = 1120,
                            AttributeID = 112,
                            ProductModelId = 778,
                            Value = "512GB SSD"
                        },
                        new
                        {
                            AttributeValueID = 1121,
                            AttributeID = 113,
                            ProductModelId = 778,
                            Value = "15.6 inches"
                        },
                        new
                        {
                            AttributeValueID = 1122,
                            AttributeID = 114,
                            ProductModelId = 1780,
                            Value = "8kg"
                        },
                        new
                        {
                            AttributeValueID = 1123,
                            AttributeID = 115,
                            ProductModelId = 1780,
                            Value = "1200 RPM"
                        },
                        new
                        {
                            AttributeValueID = 1124,
                            AttributeID = 114,
                            ProductModelId = 1781,
                            Value = "NA"
                        },
                        new
                        {
                            AttributeValueID = 1125,
                            AttributeID = 115,
                            ProductModelId = 1781,
                            Value = "NA"
                        },
                        new
                        {
                            AttributeValueID = 1126,
                            AttributeID = 116,
                            ProductModelId = 1881,
                            Value = "watchOS"
                        },
                        new
                        {
                            AttributeValueID = 1127,
                            AttributeID = 117,
                            ProductModelId = 1881,
                            Value = "Up to 18 hours"
                        },
                        new
                        {
                            AttributeValueID = 1128,
                            AttributeID = 118,
                            ProductModelId = 199,
                            Value = "Metal"
                        },
                        new
                        {
                            AttributeValueID = 1129,
                            AttributeID = 119,
                            ProductModelId = 199,
                            Value = "UV Protection"
                        },
                        new
                        {
                            AttributeValueID = 1130,
                            AttributeID = 1110,
                            ProductModelId = 199,
                            Value = "Plastic"
                        },
                        new
                        {
                            AttributeValueID = 1131,
                            AttributeID = 1111,
                            ProductModelId = 17811,
                            Value = "2.3 GHz"
                        },
                        new
                        {
                            AttributeValueID = 1132,
                            AttributeID = 1112,
                            ProductModelId = 17811,
                            Value = "6GB"
                        },
                        new
                        {
                            AttributeValueID = 1133,
                            AttributeID = 1113,
                            ProductModelId = 17811,
                            Value = "48 MP"
                        },
                        new
                        {
                            AttributeValueID = 1134,
                            AttributeID = 1114,
                            ProductModelId = 1780,
                            Value = "10kg"
                        },
                        new
                        {
                            AttributeValueID = 1135,
                            AttributeID = 1115,
                            ProductModelId = 1780,
                            Value = "1400 RPM"
                        },
                        new
                        {
                            AttributeValueID = 1136,
                            AttributeID = 1116,
                            ProductModelId = 778,
                            Value = "NVIDIA GeForce RTX 3070"
                        },
                        new
                        {
                            AttributeValueID = 1137,
                            AttributeID = 1117,
                            ProductModelId = 778,
                            Value = "1920 x 1080 pixels"
                        },
                        new
                        {
                            AttributeValueID = 1138,
                            AttributeID = 1118,
                            ProductModelId = 1781,
                            Value = "Stainless Steel"
                        },
                        new
                        {
                            AttributeValueID = 1139,
                            AttributeID = 1119,
                            ProductModelId = 1881,
                            Value = "iOS 15"
                        },
                        new
                        {
                            AttributeValueID = 1140,
                            AttributeID = 1120,
                            ProductModelId = 1881,
                            Value = "Aluminum"
                        },
                        new
                        {
                            AttributeValueID = 1141,
                            AttributeID = 1110,
                            ProductModelId = 199,
                            Value = "Glass"
                        },
                        new
                        {
                            AttributeValueID = 1142,
                            AttributeID = 1111,
                            ProductModelId = 278,
                            Value = "2.8 GHz"
                        },
                        new
                        {
                            AttributeValueID = 1143,
                            AttributeID = 1112,
                            ProductModelId = 278,
                            Value = "8GB"
                        },
                        new
                        {
                            AttributeValueID = 1144,
                            AttributeID = 1113,
                            ProductModelId = 278,
                            Value = "64 MP"
                        },
                        new
                        {
                            AttributeValueID = 1145,
                            AttributeID = 1114,
                            ProductModelId = 1781,
                            Value = "NA"
                        },
                        new
                        {
                            AttributeValueID = 1146,
                            AttributeID = 1115,
                            ProductModelId = 1781,
                            Value = "NA"
                        },
                        new
                        {
                            AttributeValueID = 1147,
                            AttributeID = 1116,
                            ProductModelId = 878,
                            Value = "NVIDIA GeForce GTX 1650"
                        },
                        new
                        {
                            AttributeValueID = 1148,
                            AttributeID = 1117,
                            ProductModelId = 878,
                            Value = "1366 x 768 pixels"
                        },
                        new
                        {
                            AttributeValueID = 1149,
                            AttributeID = 1118,
                            ProductModelId = 199,
                            Value = "Plastic"
                        },
                        new
                        {
                            AttributeValueID = 1150,
                            AttributeID = 1119,
                            ProductModelId = 199,
                            Value = "Android and iOS"
                        },
                        new
                        {
                            AttributeValueID = 1151,
                            AttributeID = 1120,
                            ProductModelId = 199,
                            Value = "Titanium"
                        });
                });

            modelBuilder.Entity("pajo22.Models.Attributes", b =>
                {
                    b.Property<int>("AttributeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeID"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubgroupId")
                        .HasColumnType("int");

                    b.HasKey("AttributeID");

                    b.HasIndex("SubgroupId");

                    b.ToTable("Attributes");

                    b.HasData(
                        new
                        {
                            AttributeID = 111,
                            AttributeName = "os",
                            SubgroupId = 111
                        },
                        new
                        {
                            AttributeID = 112,
                            AttributeName = "Storage Capacity",
                            SubgroupId = 111
                        },
                        new
                        {
                            AttributeID = 113,
                            AttributeName = "Screen Size",
                            SubgroupId = 111
                        },
                        new
                        {
                            AttributeID = 114,
                            AttributeName = "Load Capacity",
                            SubgroupId = 22
                        },
                        new
                        {
                            AttributeID = 115,
                            AttributeName = "Energy Efficiency",
                            SubgroupId = 22
                        },
                        new
                        {
                            AttributeID = 116,
                            AttributeName = "Operating System",
                            SubgroupId = 33
                        },
                        new
                        {
                            AttributeID = 117,
                            AttributeName = "Battery Life",
                            SubgroupId = 33
                        },
                        new
                        {
                            AttributeID = 118,
                            AttributeName = "Material",
                            SubgroupId = 36
                        },
                        new
                        {
                            AttributeID = 119,
                            AttributeName = "Water Resistance",
                            SubgroupId = 37
                        },
                        new
                        {
                            AttributeID = 1110,
                            AttributeName = "Lens Type",
                            SubgroupId = 39
                        },
                        new
                        {
                            AttributeID = 1111,
                            AttributeName = "Processor Speed",
                            SubgroupId = 111
                        },
                        new
                        {
                            AttributeID = 1112,
                            AttributeName = "RAM Size",
                            SubgroupId = 111
                        },
                        new
                        {
                            AttributeID = 1113,
                            AttributeName = "Camera Resolution",
                            SubgroupId = 111
                        },
                        new
                        {
                            AttributeID = 1114,
                            AttributeName = "Washing Capacity",
                            SubgroupId = 22
                        },
                        new
                        {
                            AttributeID = 1115,
                            AttributeName = "Spin Speed",
                            SubgroupId = 22
                        },
                        new
                        {
                            AttributeID = 1116,
                            AttributeName = "Graphics Card",
                            SubgroupId = 33
                        },
                        new
                        {
                            AttributeID = 1117,
                            AttributeName = "Display Resolution",
                            SubgroupId = 33
                        },
                        new
                        {
                            AttributeID = 1118,
                            AttributeName = "Strap Material",
                            SubgroupId = 36
                        },
                        new
                        {
                            AttributeID = 1119,
                            AttributeName = "Operating System Compatibility",
                            SubgroupId = 37
                        },
                        new
                        {
                            AttributeID = 1120,
                            AttributeName = "Frame Material",
                            SubgroupId = 39
                        });
                });

            modelBuilder.Entity("pajo22.Models.GroupModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GroupModels");

                    b.HasData(
                        new
                        {
                            Id = 111,
                            Name = "کالا های دیجیتال",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            Name = "لوازم خانگی",
                            Status = 0
                        },
                        new
                        {
                            Id = 323,
                            Name = "کالا های پوشیدنی",
                            Status = 0
                        });
                });

            modelBuilder.Entity("pajo22.Models.ProductModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubgroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubgroupId");

                    b.ToTable("ProductModels");

                    b.HasData(
                        new
                        {
                            Id = 17811,
                            Color = "gray",
                            Description = "mid-range Samsung",
                            Image = "/images/ph6.png",
                            Name = "سامسونگ Samsung A54",
                            Price = 13000000m,
                            Status = 0,
                            SubgroupId = 111
                        },
                        new
                        {
                            Id = 278,
                            Color = "Blue",
                            Description = "flagship Samsung",
                            Image = "/images/ph3.png",
                            Name = "سامسونگ Samsung S23",
                            Price = 2300000m,
                            Status = 0,
                            SubgroupId = 111
                        },
                        new
                        {
                            Id = 378,
                            Color = "Green",
                            Description = "it's iPhone, just buy it",
                            Image = "/images/ph1.png",
                            Name = "Iphone 13 آیفون",
                            Price = 4000000m,
                            Status = 0,
                            SubgroupId = 111
                        },
                        new
                        {
                            Id = 478,
                            Color = "Green",
                            Description = "it's cheap, why not",
                            Image = "/images/ph5.png",
                            Name = "Xiaomi Redmi شیائومی",
                            Price = 6000000m,
                            Status = 0,
                            SubgroupId = 111
                        },
                        new
                        {
                            Id = 578,
                            Color = "Green",
                            Description = "the classic from the past",
                            Image = "/images/ph6.png",
                            Name = "Classic Gold Phone گوشی کلاسیک",
                            Price = 1000000m,
                            Status = 0,
                            SubgroupId = 111
                        },
                        new
                        {
                            Id = 678,
                            Color = "Green",
                            Description = "Iranian made cheap",
                            Image = "/images/p7.png",
                            Name = "GPlus 128 gig جی پلاس",
                            Price = 4000000m,
                            Status = 0,
                            SubgroupId = 111
                        },
                        new
                        {
                            Id = 778,
                            Color = "Green",
                            Description = "Asus TUFF gaming",
                            Image = "~/images/f2.png",
                            Name = "Asus TUF Gaming ایسوس تاف",
                            Price = 64000000m,
                            Status = 0,
                            SubgroupId = 33
                        },
                        new
                        {
                            Id = 878,
                            Color = "black",
                            Description = "Acer regular laptop",
                            Image = "/images/f3.png",
                            Name = "Acer Aspire ایسر",
                            Price = 35000000m,
                            Status = 0,
                            SubgroupId = 33
                        },
                        new
                        {
                            Id = 8789,
                            Color = "black",
                            Description = "macbook from apple ",
                            Image = "/images/f43.png",
                            Name = "لپ تاپ 14.2 اینچی اپل مدل MacBook Pro MTL73 2023-M3 8GB 512SSD",
                            Price = 86000000m,
                            Status = 0,
                            SubgroupId = 33
                        },
                        new
                        {
                            Id = 8788,
                            Color = "black",
                            Description = "msi expensive laptop",
                            Image = "/images/f33.png",
                            Name = "لپ تاپ 15.6 اینچی ام اس آی مدل Katana 15 B12VEK",
                            Price = 95000000m,
                            Status = 0,
                            SubgroupId = 33
                        },
                        new
                        {
                            Id = 978,
                            Color = "black",
                            Description = "Lenovo gaming laptop",
                            Image = "/images/f1.png",
                            Name = "Lenovo Legion لنوو",
                            Price = 48000000m,
                            Status = 0,
                            SubgroupId = 33
                        },
                        new
                        {
                            Id = 1780,
                            Color = "black",
                            Description = "Snowa Iranian made washing machine",
                            Image = "/images/a1.png",
                            Name = "Snowa اسنوا لباس شویی",
                            Price = 45000000m,
                            Status = 0,
                            SubgroupId = 22
                        },
                        new
                        {
                            Id = 1781,
                            Color = "blue",
                            Description = "normal watch",
                            Image = "/images/ap2.png",
                            Name = "ساعت معمولی Q&Q",
                            Price = 2000000m,
                            Status = 0,
                            SubgroupId = 36
                        },
                        new
                        {
                            Id = 1881,
                            Color = "orange",
                            Description = "apple smart watch",
                            Image = "/images/ap1.png",
                            Name = "apple watch ساعت اپل",
                            Price = 42000000m,
                            Status = 0,
                            SubgroupId = 38
                        },
                        new
                        {
                            Id = 199,
                            Color = "black",
                            Description = "iconix glasses",
                            Image = "/images/RB1.png",
                            Name = "عینک کلاسیک rayban",
                            Price = 20000000m,
                            Status = 0,
                            SubgroupId = 39
                        });
                });

            modelBuilder.Entity("pajo22.Models.SubgroupModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentSubGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupID");

                    b.HasIndex("ParentSubGroupId");

                    b.ToTable("SubgroupModels");

                    b.HasData(
                        new
                        {
                            Id = 111,
                            GroupID = 111,
                            Name = "گوشی موبایل",
                            Status = 0
                        },
                        new
                        {
                            Id = 22,
                            GroupID = 22,
                            Name = "ماشین لباس شویی",
                            Status = 0
                        },
                        new
                        {
                            Id = 33,
                            GroupID = 111,
                            Name = "لب تاب",
                            Status = 0
                        },
                        new
                        {
                            Id = 36,
                            GroupID = 323,
                            Name = "ساعت",
                            Status = 0
                        },
                        new
                        {
                            Id = 37,
                            GroupID = 323,
                            Name = "ساعت هوشمند",
                            ParentSubGroupId = 36,
                            Status = 0
                        },
                        new
                        {
                            Id = 38,
                            GroupID = 323,
                            Name = "  ساعت هوشمند اپل",
                            ParentSubGroupId = 37,
                            Status = 0
                        },
                        new
                        {
                            Id = 39,
                            GroupID = 323,
                            Name = "  عینک",
                            Status = 0
                        },
                        new
                        {
                            Id = 40,
                            GroupID = 323,
                            Name = "  عینک های rayban",
                            ParentSubGroupId = 39,
                            Status = 0
                        });
                });

            modelBuilder.Entity("pajo22.Models.AttributeValues", b =>
                {
                    b.HasOne("pajo22.Models.Attributes", "Attribute")
                        .WithMany()
                        .HasForeignKey("AttributeID")
                        .IsRequired();

                    b.HasOne("pajo22.Models.Attributes", null)
                        .WithMany("AttributeValues")
                        .HasForeignKey("AttributesAttributeID");

                    b.HasOne("pajo22.Models.ProductModels", "ProductModel")
                        .WithMany("AttributeValues")
                        .HasForeignKey("ProductModelId")
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("ProductModel");
                });

            modelBuilder.Entity("pajo22.Models.Attributes", b =>
                {
                    b.HasOne("pajo22.Models.SubgroupModels", "Subgroup")
                        .WithMany("Attributes")
                        .HasForeignKey("SubgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subgroup");
                });

            modelBuilder.Entity("pajo22.Models.ProductModels", b =>
                {
                    b.HasOne("pajo22.Models.SubgroupModels", "Subgroup")
                        .WithMany("Product")
                        .HasForeignKey("SubgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subgroup");
                });

            modelBuilder.Entity("pajo22.Models.SubgroupModels", b =>
                {
                    b.HasOne("pajo22.Models.GroupModels", "GroupModels")
                        .WithMany("Subgroups")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pajo22.Models.SubgroupModels", "ParentSubGroup")
                        .WithMany("Children")
                        .HasForeignKey("ParentSubGroupId");

                    b.Navigation("GroupModels");

                    b.Navigation("ParentSubGroup");
                });

            modelBuilder.Entity("pajo22.Models.Attributes", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("pajo22.Models.GroupModels", b =>
                {
                    b.Navigation("Subgroups");
                });

            modelBuilder.Entity("pajo22.Models.ProductModels", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("pajo22.Models.SubgroupModels", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Children");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
